sudo: false
dist: trusty
language: php

env:
  global:
  - COMPOSER_ARGS="--no-interaction"
  - github_token:
      secure: "Iy/Plz3V++TKSQbz/A0x7ZhETSfcvbXxT4zKQh51W8fjBUlKKrQmDA1rICIjnfFs0bNAe6M2yQxxHgJKUJPBsi9Nk/Ynuk/I5lLK1jLL6THioGB6oKUyRBytlcVLZ+0lNqmV/jRKYdwEPI+jNduCk5GSjubSGMIWGNDcqAUiTu+oy3Gu9FS/auEGxim7UaZYC+MM+7ir0zD6w/0nuCaxalAeLahFz0g3QlXc7FB88SxH//lxzKDZh3U6XKyIEXGG8IQiCYaJRUqr9unzHDVbjOvNT6HWZQ4jGSfnCZTnp4aPfOrk1Ir334/4Cuy4xCP4iiuiRFHoxw++uknh77slUwRtZbrUlwoCbvT0V/GOQaN2HSjrTOc5n1/M0XsPRumbZ+I/4EoCnZUwNiBpWtVhrzSpE84+0BBj67gmStzca1sZMkts+oHnr5S6qajVY5ePY4Sn3rI/JbUJP501zexRHgqKY26a+Hqz9TAnNJqRKfm6ez5pSlXUKk4eCl7slgYuY8I="

matrix:
  allow_failures:
    - stage: acceptance-test
  include:
  - php: 5.6
    if: type != cron AND env(PHRASEAPP_PULL) != '1'
  - php: 7.0
    if: type != cron AND env(PHRASEAPP_PULL) != '1'
  - php: 7.1
    if: type != cron AND env(PHRASEAPP_PULL) != '1'

  - &acceptance-test
    stage: acceptance-test
    if: type = cron
    php: 7.1
    env: GATEWAY=API-TEST
    before_install:
    - travis_retry composer self-update
    install:
    - bash .bin/generate-release-package.sh test
    - travis_retry composer require --dev $COMPOSER_ARGS codeception/codeception
    - travis_retry composer install $COMPOSER_ARGS
    - composer show
    script: bash .bin/run-ui-tests.sh
    after_script: skip
    after_success:
    - bash .bin/upload-logs-and-notify.sh
    after_failure:
    - bash .bin/upload-logs-and-notify.sh fail
  - <<: *acceptance-test
    env: GATEWAY=API-WDCEE-TEST
  - <<: *acceptance-test
    env: GATEWAY=NOVA

  - stage: phraseapp-pull
    if: type != cron AND env(PHRASEAPP_PULL) = '1'
    language: ruby
    ruby: 2.5.3
    before_install: skip
    install:
    - travis_retry gem install bundler -v 2.0.1
    - travis_retry bundle install
    script:
    - .bin/rake phraseapp:ci_update
    after_script: skip

  - stage: phraseapp-check-if-in-sync
    if: branch = master OR type = pull_request
    language: ruby
    ruby: 2.5.3
    before_install: skip
    install:
    - travis_retry gem install bundler -v 2.0.1
    - travis_retry bundle install
    script:
    - .bin/rake phraseapp:ci_check_if_in_sync
    after_script: skip

before_install:
  - export PHPCS_DIR=/tmp/phpcs
  - export SNIFFS_DIR=/tmp/sniffs
  - git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
  - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
  - $PHPCS_DIR/bin/phpcs --config-set installed_paths $SNIFFS_DIR

install:
  - travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test-coverage
  - $PHPCS_DIR/bin/phpcs -p --ignore=*/Test/*,*/vendor/*,*/.bin/*,*/tests/* . --standard=WordPress-Core

after_script:
  - travis_retry composer upload-coverage
  - bash .bin/generate-tag.sh

before_deploy:
  - export REPO_NAME=`echo $TRAVIS_REPO_SLUG | awk -F'/' '{print $2}'`
  - export RELEASE_NOTES=$(composer make-release-notes)
  - bash .bin/generate-wiki-notes.sh
  - bash .bin/generate-readme-badge.sh
  - bash .bin/generate-release-package.sh $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: pL51FT1uFo4QfBg7kCIu843uAkf1EYuiWLevkfYsgTMLMaRoR+VcaIfCk8SmUm8JKzGHdaQFIlS8MFpxZRxNhl5nNkes6+SEyGpoC7OV8KO9y/1nxKyTXL5IOo1/ri77eV9aJt13JOl9wEEMpTDiejSJCJZN6P7jzBdo00usgmKQanZsEjMzwg0I59Kbanlj30NwLHUt3Nrdp5gyP41EJR/w826zCkjECVoAC1UFzfhd2g4l5cNDuzdpqgcXi89+ABkKZVG4f4HZhGsQG0APXdJn9jSBCc28Kgq1ubjAwxZGNmJAYOMYgVxQ9tmarZrQ67T/OHToq2lssPeX7XypV/L1YwAhYbC/I5Z06Q8UyGTd2gEZUM+8htPdpJPCyuSlzpasKfH9AJ12JjbspwtPd1CPakpU1VmVDwXhkBV/Zm8lfy8BQXY0KP6A09KJ5hklqky45xJZtlWRqAzWOniIhfo8GT2OLC8215Oc4X7LCIWMreJI8Dt4eradSK6iEA9sRjDVq3iZjNsrCD36h+nXUFnOiQwYQ0y4Hu6z/ZN1kKOKI4gDxWPnnjYnE9kJurAZ00WLMkMMrSzAEZyDj2fIecPTisK6Uo2PTxqU31Jd6VaGTvm0gFoZ8Hi5Z4hRYrskbDKvEtuqj9gtSE12yc9G5qJsjfrF/dZlrco8olSWlRk=
  file: woocommerce-wirecard-ee.zip
  name: "${REPO_NAME} ${TRAVIS_TAG}"
  body: "${RELEASE_NOTES}"
  skip_cleanup: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
    
after_deploy:
  - export TMPDIR=/tmp/wirecard
  - git clone -b master --depth 1 https://$WIRECARD_CEE_GITHUB_TOKEN@github.com/$DEPLOYMENT_PROJECT $TMPDIR
  - cd $TMPDIR && travis_retry bundle install
  - .bin/rake trigger_build

notifications:
  email: false
  slack:
    rooms:
      secure: YI7sUrfMyKyJD60kElGkO7yBDkGEh+069yS8bFAIDUST7s48J+dDP/r2G9dN9oQwhs9hvNjpNytpZDPys838T+Z0mNtFZ9Wu022hV3MpbKUuMl7L9P0MQQmxjg4bKyKK3Hl9tPrZ3UsKRlwIUmRGGYQ7cjs4zumorqs19YsB3X+WnnxAmmYB3kHQYfNKgVnmcG2QHJyx5KaLZ0EsWynSHXkYb8bVCtdlbQFNnpChvGHPprZrHAszLCYnlU7AEZGdbuk17oIfXO9Wjuu1GV8iJ2VgKkTCzW4FBC5eHJyZezojPFUm1I5tvdihRZuyBekVGOF23J6pvHLqPx77clT+/Vn6T+UMDuh1INZ0LKt4UOU42oEDKGblWZx2VYWcHwfEK+ckJWZkT9EBfg/CMenJly2tbtBj6++XNvxgGEDn6XqKIEatcb7X/aiy4f8BPXa3/pzgZAlvzZbGGqHFNZPAlgcXBBXgbaC7VvMhvi6Z5AG5ylKzPS5GCD95ozPC+cGv0234TBJus5oZck4qNiT53IUQ7Ta+OGVB0Mea105VAoQI0I7YcgaqW6c4h2YTmnuuQsIzAwPOrJ5TAinj8Z8mZ9C11tEcNF3Pgy1tOoG/YLurhOJm7v1ebotRb/DIeSHU8RfNatnDSSky4YS6Y8k2pQthdC9m7m2f2mJYuGdLjlM=
    template:
      - "%{repository}#%{build_number} (%{branch} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: change
